.PHONY: build
build: ## Installing requirements and initiating tox
	@python -m pip install -r requirements.txt

.PHONY: tox-init
tox-init: ## Installing requirements and initiating tox
	@python -m pip install -r requirements.txt

.PHONY: build
build: ## Installing requirements and initiating tox
	@python -m pip install -r requirements.txt